void main(){
  // Number : int
  int value=10;
  var x=10;  // automatically identifies data type


  // Number : double
  double num=92.0;
  var d=982.67;


  // String :
  String str='Battu';
  var s="Vasanth";


  // Boolean :
  bool isValid=false;
  var isEligible=true;
  
  /* Note: variable is an object 
  By default it stores Null value*/


  print(value);
  print(x);
  print(num);
  print(d);
  print(str);
  print(s);
  print(isValid);
  print(isEligible);


}
